name: Ecommerce CI/CD

on:
  push:
    branches:
      - main

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test -- --ci

      - name: Build app
        run: npm run build
    
    
  deploy:
    needs: test-and-build
    runs-on: ubuntu-latest

    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: 22

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel configuration
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Pull production environment variables
        run: vercel env pull .env.production.local --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Check Firebase env file
        run: |
          if grep -q "^VITE_FIREBASE_API_KEY=" .env.production.local; then
            echo "Firebase API key exists in pulled production env"
          else
            echo "Firebase API key is missing"
            exit 1
          fi

      - name: Build with Vercel
        run: |
            set -a
            source .env.production.local
            set +a
            vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}          

      - name: Build with Vercel
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Check Vercel identity
        run: vercel whoami --token=${{ secrets.VERCEL_TOKEN }}